NUMBER_OF_SAMPLES = 100

TRAIN_PERCENT = 0.9
VALIDATE_PERCENT = 0.1
CLASS1_NAME = "dogs"
CLASS2_NAME = "cats"

ALL_FOLDER_NAME = "all"
SAMPLES_FOLDER_NAME="samples"
DATA_FOLDER_NAME = "data"
TRAIN_FOLDER_NAME = "train"
VALIDATE_FOLDER_NAME = "validate"
KAGGLE_TEST_FOLDER_NAME="test"






